In [1]:
import cv2
import numpy as np

## Exercise:
### Track red, blue and green together in video

In [3]:
bl = np.uint8([[[255,0,0]]])
hsv_bl = cv2.cvtColor(bl,cv2.COLOR_BGR2HSV)
print hsv_bl

[[[120 255 255]]]


In [5]:
rd = np.uint8([[[0,0,255]]])
hsv_rd = cv2.cvtColor(rd,cv2.COLOR_BGR2HSV)
print hsv_rd

[[[  0 255 255]]]


In [6]:
gr = np.uint8([[[0,255,0]]])
hsv_gr = cv2.cvtColor(gr,cv2.COLOR_BGR2HSV)
print hsv_gr

[[[ 60 255 255]]]


In [7]:
cap = cv2.VideoCapture(0)
while(1):
    _, frame  = cap.read()
    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    lower_blue = np.array([110,50,50])
    upper_blue = np.array([130,255,255])
    lower_green = np.array([50,50,50])
    upper_green = np.array([70,255,255])
    lower_red = np.array([0,50,50])
    upper_red = np.array([20,255,255])
    mask1 = cv2.inRange(hsv,lower_blue,upper_blue)
    res1 = cv2.bitwise_and(frame,frame,mask= mask1)
    mask2 = cv2.inRange(hsv,lower_green,upper_green)
    res2 = cv2.bitwise_and(frame,frame,mask= mask2)
    mask3 = cv2.inRange(hsv,lower_red,upper_red)
    res3 = cv2.bitwise_and(frame,frame,mask= mask3)
    temp = cv2.add(res1,res2)
    res = cv2.add(temp,res3)
    cv2.imshow('frame',frame)
    #cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()